# Generated by Django 4.2.9 on 2024-11-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
