# Generated by Django 4.2.9 on 2024-11-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_ultima_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='detalles',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
