# Generated by Django 4.2.9 on 2024-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cita_motivo_remove_doctor_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_doctores/'),
        ),
    ]
